export const ADD_PROJECT = 'ADD_PROJECT'
export const EDIT_PROJECT = 'EDIT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DEFINE_PROJECTS = 'DEFINE_PROJECTS'


export const NOTIFY = 'NOTIFY'